const express = require('express')
const app= express()
const cors= require('cors')
const userroute=require("./router/user.route")
const emiroute = require("./router/emi.route")
const mongoose=require('mongoose')
const dotenv= require("dotenv").config()
mongoose.connect(process.env.MONGO_URL).then(()=>{console.log("Running")}).catch((err)=>{console.log(err)})
app.use(cors())
app.use(express.json())
app.use("/user",userroute)
app.use("/emi",emiroute)

app.listen(process.env.PORT|| 8080,()=>{console.log("Listening At PORT No. 8080");})